// <auto-generated />
using System;
using BankingSystem.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankingSystem.Persistence.Migrations
{
    [DbContext(typeof(BankingSystemDbContext))]
    [Migration("20181205114307_Seeding")]
    partial class Seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankingSystem.Domain.Entities.AccountStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.Property<decimal>("ClosingBalance");

                    b.Property<DateTime>("StatementDateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("StatementDetails")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Statements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d957e32-d3d1-4554-8543-78ccfb432988"),
                            AccountId = new Guid("29ecb256-899e-4684-b3df-638766a60fa1"),
                            ClosingBalance = 0m,
                            StatementDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatementDetails = "This statement on Dec, 2018"
                        },
                        new
                        {
                            Id = new Guid("f497976c-b913-42c6-8a56-15c6e08cc940"),
                            AccountId = new Guid("deeec4fc-a1d0-49a4-9187-3e65ad5db4aa"),
                            ClosingBalance = 0m,
                            StatementDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatementDetails = "This statement on Dec, 2018"
                        },
                        new
                        {
                            Id = new Guid("5ae8336b-2060-4d78-832a-ab0176f5303a"),
                            AccountId = new Guid("c6538a28-9164-4634-a39c-d57433f261f0"),
                            ClosingBalance = 0m,
                            StatementDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatementDetails = "This statement on Dec, 2018"
                        });
                });

            modelBuilder.Entity("BankingSystem.Domain.Entities.AccountTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.Property<string>("Action")
                        .IsRequired();

                    b.Property<decimal>("Amount");

                    b.Property<string>("Note");

                    b.Property<DateTime>("TransactionDatetime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("025a133a-60ac-47e5-879d-509b40d25010"),
                            AccountId = new Guid("29ecb256-899e-4684-b3df-638766a60fa1"),
                            Action = "Deposit",
                            Amount = 100m,
                            Note = "This is the initial deposit.",
                            TransactionDatetime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2dcaeba6-d4ba-4234-8768-e32323328597"),
                            AccountId = new Guid("deeec4fc-a1d0-49a4-9187-3e65ad5db4aa"),
                            Action = "Deposit",
                            Amount = 200m,
                            Note = "This is the initial deposit.",
                            TransactionDatetime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("620ef155-4e10-4fd7-a3ca-4da76cd74150"),
                            AccountId = new Guid("c6538a28-9164-4634-a39c-d57433f261f0"),
                            Action = "Deposit",
                            Amount = 300m,
                            Note = "This is the initial deposit.",
                            TransactionDatetime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BankingSystem.Domain.Entities.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(30);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Currency")
                        .HasMaxLength(10);

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("LastActivityDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29ecb256-899e-4684-b3df-638766a60fa1"),
                            AccountNumber = "4111111111111111",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "THB",
                            IsActive = true,
                            LastActivityDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("deeec4fc-a1d0-49a4-9187-3e65ad5db4aa"),
                            AccountNumber = "4222222222222222",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "USD",
                            IsActive = true,
                            LastActivityDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c6538a28-9164-4634-a39c-d57433f261f0"),
                            AccountNumber = "4333333333333333",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "EUR",
                            IsActive = true,
                            LastActivityDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BankingSystem.Domain.Entities.AccountStatement", b =>
                {
                    b.HasOne("BankingSystem.Domain.Entities.BankAccount", "Account")
                        .WithMany("Statements")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BankingSystem.Domain.Entities.AccountTransaction", b =>
                {
                    b.HasOne("BankingSystem.Domain.Entities.BankAccount", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
